version: '3'
services:
  pgsql:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    restart: always
    environment:
      POSTGRES_USER: pulp
      POSTGRES_PASSWORD: pulp
    #volumes:
      #- "/etc/localtime:/etc/localtime:ro"
      #- "pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks: 
      - pulp_net

  redis:
    depends_on:
      - pgsql
    image: 'redis:4-alpine'
    ports:
      - 6379:6379
    networks: 
      - pulp_net

  pulp:
    depends_on:
      - pgsql
      - redis
    image: tchellomello/pulp-base:nightly
    command:
      - "yes"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    restart: always
    environment:
      PULP_DB_HOST: pgsql
      PULP_DB_NAME: pulp
      PULP_DB_USERNAME: pulp
      PULP_DB_PASSWORD: pulp
      PULP_DB_PORT: 5432
      PULP_REDIS_HOST: redis
      PULP_REDIS_PORT: 6379
    networks: 
      - pulp_net





#volumes:
  #pgdata:

networks:
  pulp_net: